### ISSUE TITLE
Example stops working in version 2022.12.0.

### ISSUE THREAD

**Issue by dukes4** [mochipon/hassio-uhubctl#4]
Hello 

Looks like the example needs to be adjusted - unfortunately, I was not successful in doing it myself. Any help or update would be appreciated.

Thanks, Rolf

Details from the Repair Recommendation:
Your manually configured MQTT switch(s) needs attention
This stops working in version 2022.12.0. Please address before upgrading.
Manually configured MQTT switch(s) found under platform key switch.

Please move the configuration to the mqtt integration key and restart Home Assistant to fix this issue. See the [documentation](https://www.home-assistant.io/integrations/switch.mqtt/#new_format), for more information.

**Comment by mochipon** [comment]
Hello Rolf, 

How about the following code? If you already have the `mqtt` section, you will need to merge it.

```yaml
mqtt:
  switch:
    - name: USB Fan
      unique_id: usb-fan
      icon: "mdi:fan"
      state_topic: "tele/uhubctl/localhost/HUB3-4/STATE"
      value_template: "{{ value_json.POWER1 }}"
      command_topic: "cmnd/uhubctl/localhost/HUB3-4/POWER1"
      availability_topic: "tele/uhubctl/localhost/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
```
